config/routes.rb
Rails.application.routes.draw do

	root 'network#index'

  #User Login Web Routes
	get 'login', to: 'sessions#new'
	get 'logout', to: 'sessions#destroy'
	post 'sessions', to: 'sessions#create'

  #User Web Routes
	get 'users/list', to: 'users#user_list'
	resources :users, except: [:index, :show]

	#Routes for plugin ajax calls
	get 'plugins/gateway', to: 'plugins#get_gateway'
	get 'plugins/nodes', to: 'plugins#get_nodes'
	get 'plugins/fields', to: 'plugins#get_fields'
	get 'plugins/data', to: 'plugins#get_field_data'
	get 'plugins/commands', to: 'plugins#get_gateway_commands'
	post 'plugins/command', to: 'plugins#create_gateway_command'

  #Plugin Web Routes
  get 'plugins/my_plugins', to: 'plugins#my_plugins'
  get 'plugins/tutorial', to: 'plugins#tutorial'
  resources :plugins, except: [:new]

  #Network Web Routes
	post 'network/connect', to: 'network#connect'
	post 'network/update', to: 'network#update'
	get 'network', to: 'network#index'

  #Node Web Routes
	resources :nodes, only: [:show]
	get 'update', to: 'nodes#update'

  #Gateway Web Routes
	resources :gateways, only: [:show]

  #Access Rights Web Routes
	resources :access_rights, only: [:index, :create, :destroy]

  #Devices Routes
  put 'devices/addlinknodetogateway',to: 'devices#add_link_node_to_gateway'
  put 'devices/removelinknodetogateway',to: 'devices#remove_link_node_to_gateway'
	get 'devices/queuednodecount', to: 'devices#number_of_queued_nodes'
	put 'devices/acceptedqueuednode', to: 'devices#accept_queued_node'
	put 'devices/rejectqueuednode', to: 'devices#reject_queued_node'
	resources :devices

  #Windows Web Routes
	resources :windows, only: [:show, :create, :destroy] do
		member do 
			put :backward
			put :forward
			put :resize
		end
	end

  #Command Web Routes
	resources :commands, only: [:show, :create, :destroy, :update]do
		member do 
			get :execute
      get :next
		end
  end
  post 'commands/:command_id/parameter', to: 'commands#create_param'
	put 'commands/:command_id/parameter/:param_id', to: 'commands#update_param'
	delete 'commands/:command_id/parameter/:param_id', to: 'commands#destroy_param'
	#get 'commands/next', to: 'commands#next'

  #Field Web Routes
	resources :fields, only: [:create, :update, :destroy]

  #Data Web Routes
	resources :data, only: [:index, :create]
  get 'data/export_data', to: 'data#export_data'

  #Settings Web Routes
  get 'settings/nodetypes', to: 'settings#picklist'
	get 'settings/commandtypes', to: 'settings#picklist'
  resources :settings, only: [:index, :update, :destroy]

  ### MOBILE API ROUTES ###
  namespace :mobileapi do
    #Data
		put 'data', to: 'data#create', defaults: {format: :json}
		post 'data', to: 'data#create_mult', defaults: {format: :json}
		post 'datafile', to: 'data#create_via_file', defaults: {format: :json}

    #Commands
    get 'command', to: 'command#show', defaults: {format: :json}
    put 'command', to: 'command#next', defaults: {format: :json}

    #Devices
    put 'devices/approvalrequest', to: 'device_approval_queue#device_approval_request', defaults: {format: :json}
    post 'devices/approvalrequest', to: 'device_approval_queue#device_approval_request', defaults: {format: :json}
    get 'devices', to: 'device_approval_queue#registered_devices', defaults: {format: :json}
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
	before_filter :authorize

	def show
		@node = current_user.devices.find_by_id params[:id]
		if @node
			@plugins = Plugin.where(type: :Node)
				.where(is_protected: false)
				.concat(current_user.plugins.where(type: :Node))
				.uniq
			@windows = @node.windows.order(:index)
			@fields = @node.fields

			settings = Setting.where(item_code: 'nodetype')
			@field_types = []
			if !settings.nil? && !settings.empty?
				settings.map do |setting|
					@field_types << setting.item_description
				end
			end
		elsif Node.find_by_id params[:id]
			flash[:error] = 'User does not have access rights to the node'
			redirect_to network_path
		else
			flash[:error] = 'Node does not exist'
			redirect_to network_path
		end
	end

end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'devices/device_show' %>
	<%= javascript_include_tag 'node_show' %>

	<%= stylesheet_link_tag 'devices/devices' %>
	<%= stylesheet_link_tag 'nodes' %>
<% end %>

<div class="row">
	<h4 class="breadcrumb">
    <%= render 'layouts/backbutton' %>
    <%= t('node_view') %>
  </h4>
</div>

<div id="node-container" class="row" data-id="<%=@node.id%>">
	<ul class="nav nav-tabs">
		<li role="presentation" class="active"><a href="javascript:;" id="dock-link"><%= t('node_dock') %></a></li>
		<li role="presentation"><a href="javascript:;" id="settings-link"><%= t('node_settings') %></a></li>
	</ul>

	<div id="node-dock">
    <div class="dock-form well well-sm">
      <% unless @plugins.nil? %>
        <%= form_for :window, url: windows_path, method: :post, html: { class: "form-inline" } do |f| %>
          <%= f.text_field :device_id, value: @node.id, style: 'display:none;' %>
          <div class="form-group">
            <% p_list = @plugins.map{|p| [p.name, p.id]}.unshift(['','Default']) %>
            <%= f.select :plugin_id, p_list, {}, { selected: 'Default', class: "form-control" } %>
          </div>
          <div class="form-group">
            <%= f.submit class: "btn btn-primary", value: t('window_add')  %>
          </div>
        <% end %>
      <% end %>
    </div>

		<% unless @windows.nil? %>
			<% @windows.each do |window| %>
				<%= render "windows/show", window: window, device_id: @node.id %>
			<% end %>
		<% end %>
	</div>

	<div id="node-settings" style="display:none">
		<div class="row" style="margin-bottom:5px;">
			<div class="col-sm-2 setting-text"> <b> <%= t('node_name') %>: </b> </div>
			<div class="col-sm-10 setting-text"> <%= @node.name %> </div>
		</div> 
		<div class="row" style="margin-bottom:5px;">
			<div class="col-sm-2 setting-text"> <b> <%= t('node_id') %>: </b> </div>
			<div class="col-sm-10 setting-text">
        <% if @node.node_id.nil? %>
            <span style="color:gray">Missing</span>
        <% else %>
          <%= @node.node_id %>
        <% end %>
      </div>
		</div>
    <div class="row" style="margin-bottom:5px;">
      <div class="col-sm-2 setting-text"> <b> address: </b> </div>

      <div class="col-sm-10 setting-text">
        <% if @node.address.nil? %>
            <span style="color:gray">Unknown</span>
        <% else %>
            <%= @node.address %>
        <% end %>
      </div>
    </div>
    <div class="row" style="margin-bottom:5px;">
      <div class="col-sm-2 setting-text"> <b> <%= t('node_key') %>: </b> </div>
      <div class="col-sm-10 setting-text"> <%= @node.key.value %> </div>
    </div>
    <br/>

		<br/>
		<div class="row">
			<div class="col-xs-1"><%= t('node_sensor_id') %></div>
			<div class="col-xs-4"><%= t('node_sensor_name') %></div>
      <div class="col-xs-3">Field Type</div>
      <div class="col-xs-2">&nbsp;</div>
      <div class="col-xs-2">Export Data</div>
		</div>
		<br/>

		<% unless @fields.nil? %>
      <div class="field-list">
        <% @fields.each do |field| %>
          <%= render 'fields/form', field: field %>
        <% end %>
      </div>
		<% end %>

    <div class="buttons">
      <%= form_for :field, url: fields_path, method: :post do |f| %>
        <%= f.text_field :device_id, value: @node.id, style: 'display:none;' %>
        <button type="button" href="javascript:;" id="add-field" class="btn btn-primary"><%= t('node_sensor_addfield') %></button>
      <% end %>
      <button type="button" class="btn btn-primary" id="update-fields"><%= t('node_sensor_updatefields') %></button>
    </div>
	</div>
</div>