config/routes.rb
Rails.application.routes.draw do

	root 'network#index'

  #User Login Web Routes
	get 'login', to: 'sessions#new'
	get 'logout', to: 'sessions#destroy'
	post 'sessions', to: 'sessions#create'

  #User Web Routes
	get 'users/list', to: 'users#user_list'
	resources :users, except: [:index, :show]

	#Routes for plugin ajax calls
	get 'plugins/gateway', to: 'plugins#get_gateway'
	get 'plugins/nodes', to: 'plugins#get_nodes'
	get 'plugins/fields', to: 'plugins#get_fields'
	get 'plugins/data', to: 'plugins#get_field_data'
	get 'plugins/commands', to: 'plugins#get_gateway_commands'
	post 'plugins/command', to: 'plugins#create_gateway_command'

  #Plugin Web Routes
  get 'plugins/my_plugins', to: 'plugins#my_plugins'
  get 'plugins/tutorial', to: 'plugins#tutorial'
  resources :plugins, except: [:new]

  #Network Web Routes
	post 'network/connect', to: 'network#connect'
	post 'network/update', to: 'network#update'
	get 'network', to: 'network#index'

  #Node Web Routes
	resources :nodes, only: [:show]
	get 'update', to: 'nodes#update'

  #Gateway Web Routes
	resources :gateways, only: [:show]

  #Access Rights Web Routes
	resources :access_rights, only: [:index, :create, :destroy]

  #Devices Routes
  put 'devices/addlinknodetogateway',to: 'devices#add_link_node_to_gateway'
  put 'devices/removelinknodetogateway',to: 'devices#remove_link_node_to_gateway'
	get 'devices/queuednodecount', to: 'devices#number_of_queued_nodes'
	put 'devices/acceptedqueuednode', to: 'devices#accept_queued_node'
	put 'devices/rejectqueuednode', to: 'devices#reject_queued_node'
	resources :devices

  #Windows Web Routes
	resources :windows, only: [:show, :create, :destroy] do
		member do 
			put :backward
			put :forward
			put :resize
		end
	end

  #Command Web Routes
	resources :commands, only: [:show, :create, :destroy, :update]do
		member do 
			get :execute
      get :next
		end
  end
  post 'commands/:command_id/parameter', to: 'commands#create_param'
	put 'commands/:command_id/parameter/:param_id', to: 'commands#update_param'
	delete 'commands/:command_id/parameter/:param_id', to: 'commands#destroy_param'
	#get 'commands/next', to: 'commands#next'

  #Field Web Routes
	resources :fields, only: [:create, :update, :destroy]

  #Data Web Routes
	resources :data, only: [:index, :create]
  get 'data/export_data', to: 'data#export_data'

  #Settings Web Routes
  get 'settings/nodetypes', to: 'settings#picklist'
	get 'settings/commandtypes', to: 'settings#picklist'
  resources :settings, only: [:index, :update, :destroy]

  ### MOBILE API ROUTES ###
  namespace :mobileapi do
    #Data
		put 'data', to: 'data#create', defaults: {format: :json}
		post 'data', to: 'data#create_mult', defaults: {format: :json}
		post 'datafile', to: 'data#create_via_file', defaults: {format: :json}

    #Commands
    get 'command', to: 'command#show', defaults: {format: :json}
    put 'command', to: 'command#next', defaults: {format: :json}

    #Devices
    put 'devices/approvalrequest', to: 'device_approval_queue#device_approval_request', defaults: {format: :json}
    post 'devices/approvalrequest', to: 'device_approval_queue#device_approval_request', defaults: {format: :json}
    get 'devices', to: 'device_approval_queue#registered_devices', defaults: {format: :json}
  end
end

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  name        :string(255)
#  device_type :integer
#

class Device < ActiveRecord::Base
	has_many :access_rights, :dependent => :destroy
	has_many :users, through: :access_rights
	has_many :windows, :dependent => :destroy
	has_one :key, :dependent => :destroy
  has_many :fields, :dependent => :destroy
  has_many :commands, :dependent => :destroy
  has_many :device_approval_queues, :dependent => :destroy

	validates :name, presence: true

  def next_command params
    coms = commands
    coms = coms.where(name: params[:name]) if params[:name]
    coms = coms.where(priority: params[:priority]) if params[:priority]
    coms.order(priority: :asc, created_at: :asc).first
  end

  def is_node
    device_type == "Node"
  end

  def is_gateway
    device_type == "Gateway"
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
	before_filter :authorize
	before_filter :is_admin

	def index
		require 'ostruct'
		removeIds = ""
		gateways = Device.where(device_type: "Gateway")
		@deviceTrees = []
		gateways.each do |gateway|
			deviceTree = OpenStruct.new
			deviceTree.gateway = gateway
			nodes = []
			begin
				links = DeviceToDeviceLink.where(parent:gateway.id)
				links.each do |link|
					node = Device.find(link.child)
					nodes.push(node)
					removeIds += "#{node.id},"
				end
				deviceTree.nodes = nodes
			end
			@deviceTrees.push(deviceTree)
		end
		removeIds = removeIds.chomp(",")
		@devices = Device.where(device_type: "Node")
		if removeIds != ""
			@devices = @devices.where("id not in (#{removeIds})")
		end
		@queued_nodes = nodes_queued_for_approval
	end

	def new 
		@device = Device.new
		#TODO: Can't added device unless it request to join network (maybe)
	end

	def show
		@device = current_user.devices.find_by_id params[:id]

		if @device.device_type == "Node"
			redirect_to node_path @device.id
		elsif @device.device_type == "Gateway"
			redirect_to gateway_path @device.id
		elsif @device
			flash[:error] = 'Unknown device type'
			redirect_to network_path
		else 
			flash[:error] = 'Device not found'
			redirect_to network_path
		end 
	end

	def create
		#TODO: Can't added device unless it request to join network (maybe)
		@device = Device.new device_params
		@name = @device.name
		@type = @device.device_type
		if @device.save
			if @device.node_id.nil?
				@device.update(node_id: @device.id)
			end
			key = Key.generate_key
			key.device_id = @device.id
			if key.save
				redirect_to devices_path
			else 
				if @device.destroy
					flash[:error] = 'Could not save key.'
				else
					flash[:error] = 'Could not save key and device not destroyed. Database correction needed'
				end
				render 'new'
			end
		else
			flash[:error] = 'Could not save device.'
			render 'new'
		end
	end

	def edit
		@device = Device.find params[:id]
	end

	def update
		@device = Device.find params[:id]
		if @device.update device_params
			redirect_to devices_path
		else
			flash[:error] = 'Could not update device.'
			redirect_to edit_device_path(params[:id])
		end
	end

	def destroy
		@device = Device.find params[:id]
		if @device.destroy
			DeviceToDeviceLink.where("child = " + params[:id] + " OR parent = " + params[:id]).delete_all
			redirect_to devices_path
		else
			flash[:error] = 'Could not destroy device.'
			redirect_to devices_path
		end
	end

	def add_link_node_to_gateway
		begin
			link = DeviceToDeviceLink.find_by_child(params[:node_id])
			if link.update(parent:params[:gateway_id])
				render json: {success: "Successfully linked Node Id: #{params[:node_id]} to Gateway Id: #{params[:gateway_id]}"}
			else
				render json: {error: "Unable to link Node Id: #{params[:node_id]} to Gateway Id: #{params[:gateway_id]}"}
			end
		rescue
			link = DeviceToDeviceLink.new
			link.parent = params[:gateway_id]
			link.child = params[:node_id]
			if link.save
				render json: {success: "Successfully linked Node Id: #{params[:node_id]} to Gateway Id: #{params[:gateway_id]}"}
			else
				render json: {error: "Unable to link Node Id: #{params[:node_id]} to Gateway Id: #{params[:gateway_id]}"}
			end
		end
	end

	def remove_link_node_to_gateway
		begin
			link = DeviceToDeviceLink.find_by_child(params[:node_id])
			gateway_id = link.parent
			if link.destroy
				remove_node_cmd = Command.new(name:"remove-node",priority:1,device_id:gateway_id,active:true)
				remove_node_cmd.save
				remove_node_param = Parameter.new(name:"node",value:params[:node_id],command_id:remove_node_cmd.id)
				remove_node_param.save
				render json: {success: "Successfully removed link between Node Id: #{params[:node_id]} and Gateway Id: #{gateway_id}"}
			else
				render json: {error: "Unable to remove link between Node Id: #{params[:node_id]} and Gateway Id: #{gateway_id}"}
			end
		rescue
			render json: {error: "No links for Node Id: #{params[:node_id]}"}
		end
	end

	def accept_queued_node
		#TODO: Allow users to set device Ids (possibly restrict based on Ids of other associated nodes to gateway)
		queued_node = DeviceApprovalQueue.find_by_id(params[:id])
		device = Device.new(name: "node#{params[:id]}", device_type: "Node", address: queued_node.address)
		if device.save
			if device.node_id.nil?
				device.update(node_id: device.id)
			end
			key = Key.generate_key
			key.device_id = device.id
			if key.save
				queued_node.destroy
				redirect_to devices_path
				return
			else
				if @device.destroy
					flash[:error] = 'Could not save key.'
				else
					flash[:error] = 'Could not save key and device not destroyed. Database correction needed'
				end
				redirect_to new_device_path
				return
			end
		else
			flash[:error] = 'Could not save device.'
			redirect_to new_device_path
			return
		end
		redirect_to devices_path
	end

	def reject_queued_node
		queued_node = DeviceApprovalQueue.find_by_id(params[:id])
		queued_node.destroy

		redirect_to devices_path
	end

	def number_of_queued_nodes
		nodes = nodes_queued_for_approval
		if nodes.nil?
			render json: 0
		else
			render json: nodes.length
		end
	end

	private

	def device_params
		params.require(:device).permit(:name, :device_type, :address, :node_id)
	end

	def nodes_queued_for_approval
		user_gateways = current_user.devices.where(device_type: 'Gateway');
		if user_gateways
			return DeviceApprovalQueue.all.where(device_id: user_gateways.ids)
		end
		return nil;
	end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/edit.html.erb
<div class="row">
  <h4 class="breadcrumb">
    <%= render 'layouts/backbutton' %>
    Edit Device
  </h4>
</div>
<div class="container">
  <%= form_for :device, url: device_path(@device.id), method: :put, html: { class: "form-inline" } do |f| %>

    <div class="form-group">
      <label for="device_device_type" class="col-form-label">Device Type:</label>
      <p id="device_device_type" class="form-control-static" style="display: inline-block;margin-right:5px"><%= @device.device_type %></p>
      <% if false %> <!-- used to make this section not run (basically comment it out) -->
          <%= f.select :device_type, [['Node', 'Node'], ['Gateway', 'Gateway']], {}, { selected: @device.device_type, class: "form-control" } %>
      <% end %>
    </div>

    <div class="form-group">
      <label for="device_name" class="col-form-label">Name:</label>
      <%= f.text_field :name, class: "form-control", value: @device.name, placeholder: "Name" %>
    </div>

    <div class="form-group">
      <label for="device_address" class="col-form-label">Address:</label>
      <%= f.text_field :address, class: "form-control", value: @device.address, placeholder: "Address" %>
    </div>

    <% if @device.is_node %>
      <div class="form-group">
        <label for="device_node_id" class="col-form-label">Node Id:</label>
        <%= f.text_field :node_id, class: "form-control", value: @device.node_id, placeholder: "Node Id", type: "number" %>
      </div>
    <% end %>

    <div class="form-group">
      <label for="commit" class="col-form-label"></label>
      <%= f.submit class: "btn btn-primary", value: "Save"  %>
    </div>
  <% end %>
</div>

app/views/devices/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'devices/devices_list' %>
  <%= stylesheet_link_tag 'devices/devices_list' %>
<% end %>

<div class="row">
  <h4 class="breadcrumb">
    Devices
    <%= link_to 'New Device', new_device_path, class: 'btn btn-primary', role: 'button' %>
  </h4>
</div>

<div class="row">
  <div class="col-md-12">
    <% unless @devices.nil? %>
      <table class="table table-borderless table-striped available-node-list">
        <thead>
          <tr>
            <th class="sort-selector"></th>
            <th id="name">Name</th>
            <th id="type">Type</th>
            <th id="key">Key</th>
            <th id="address">Address</th>
            <th id="nodeId">Id</th>
            <th id="editTd"></th>
            <th id="deleteTd"></th>
          </tr>
        </thead>
        <tbody class="sortable-tablebody free-node-drop-list">
        <% @devices.each do |device| %>
          <tr class="sortable-node">
            <input type="hidden" id="id" value="<%= device.id %>" />
            <td class="sort-selector"><span class="glyphicon glyphicon-move" aria-hidden="true"></span></td>
            <td id="name" class="text"><%= device.name %></td>
            <td id="type" class="text"><%= device.device_type %></td>
            <td id="key" class="text"><%= device.key.value %></td>
            <td id="address" class="text">
              <% if device.address.nil? %>
                <span style="color:gray">Unknown</span>
              <% else %>
                <%= device.address %>
              <% end %>
            </td>
            <td id="nodeId" class="text">
              <% if device.is_node && !device.node_id.nil? %>
                  <%= device.node_id %>
              <% end %>
            </td>
            <td id="editTd"><%= link_to 'Edit', edit_device_path(device.id), class: 'btn btn-primary', role: 'button' %> </td>
            <td id="deleteTd"><%= link_to 'Remove', device_path(device.id), method: :delete, data: { confirm: "Delete device?" }, class: 'btn btn-primary', role: 'button' %> </td>
          </tr>
        <% end %>
        <tr class="empty-node-list"><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
        </tbody>
      </table>
      <% @deviceTrees.each do |deviceTree| %>
        <table class="table table-borderless table-striped">
          <thead>
            <tr>
              <th></th>
              <th>Name</th>
              <th>Type</th>
              <th>Key</th>
              <th>Address</th>
              <th>Id</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody class="sortable-tablebody node-drop-zone">
            <tr class="gateway-row">
              <input type="hidden" id="id" value="<%= deviceTree.gateway.id %>" />
              <td></td>
              <td id="name" class="text"><%= deviceTree.gateway.name %></td>
              <td id="type" class="text"><%= deviceTree.gateway.device_type %></td>
              <td id="key" class="text"><%= deviceTree.gateway.key.value %></td>
              <td id="address" class="text">
                <% if deviceTree.gateway.address.nil? %>
                    <span style="color:gray">Unknown</span>
                <% else %>
                    <%= deviceTree.gateway.address %>
                <% end %>
              </td>
              <td id="nodeId" class="text">
                <% if !deviceTree.gateway.id.nil? %>
                    <%= deviceTree.gateway.id %>
                <% end %>
              </td>
              <td id="editTd"><%= link_to 'Edit', edit_device_path(deviceTree.gateway.id), class: 'btn btn-primary', role: 'button' %> </td>
              <td id="deleteTd"><%= link_to 'Remove', device_path(deviceTree.gateway.id), method: :delete, data: { confirm: "Delete device?" }, class: 'btn btn-primary', role: 'button' %> </td>
            </tr>
            <% deviceTree.nodes.each do |node| %>
              <tr class="sortable-node">
                <input type="hidden" id="id" value="<%= node.id %>" />
                <td class="sort-selector"><span class="glyphicon glyphicon-move" aria-hidden="true"></span></td>
                <td id="name" class="text"><%= node.name %></td>
                <td id="type" class="text"><%= node.device_type %></td>
                <td id="key" class="text"><%= node.key.value %></td>
                <td id="address" class="text">
                  <% if node.address.nil? %>
                      <span style="color:gray">Unknown</span>
                  <% else %>
                      <%= node.address %>
                  <% end %>
                </td>
                <td id="nodeId" class="text">
                  <% if node.is_node && !node.node_id.nil? %>
                      <%= node.node_id %>
                  <% end %>
                </td>
                <td id="editTd"><%= link_to 'Edit', edit_device_path(node.id), class: 'btn btn-primary', role: 'button' %> </td>
                <td id="deleteTd"><%= link_to 'Remove', device_path(node.id), method: :delete, data: { confirm: "Delete device?" }, class: 'btn btn-primary', role: 'button' %> </td>
              </tr>
            <% end%>
          </tbody>
        </table>
      <% end %>
    <% end %>

  </div>
</div>

<% if not (@queued_nodes.nil? || @queued_nodes.empty?)%>
  <div class="row">
    <h4 class="breadcrumb">Awaiting Approval</h4>
  </div>

  <div class="row">
    <div class="col-md-12">
      <% unless @queued_nodes.nil? %>
          <table class="table table-borderless table-striped">
            <thead>
            <tr>
              <th>Address</th>
              <th>Gateway Id</th>
              <th>Queued Date</th>
              <th></th>
              <th></th>
            </tr>
            </thead>
            <% @queued_nodes.each do |queued_node| %>
                <tr>
                  <td id="name"><%= queued_node.address %></td>
                  <td id="type"><%= queued_node.device_id %></td>
                  <td id="key"><%= queued_node.created_at %></td>
                  <td><%= link_to 'Accept', devices_acceptedqueuednode_path(id: queued_node.id), method: :put, class: 'btn btn-primary', role: 'button' %> </td>
                  <td><%= link_to 'Reject', devices_rejectqueuednode_path(id: queued_node.id), method: :put, data: { confirm: "Delete device?" }, class: 'btn btn-primary', role: 'button' %> </td>
                </tr>
            <% end %>
          </table>
      <% end %>
    </div>
  </div>
<% end %>

app/views/devices/new.html.erb
<div class="row">
  <h4 class="breadcrumb">
    <%= render 'layouts/backbutton' %>
    Add Device
  </h4>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form_for :device, url: devices_path, method: :post, html: { class: "form-inline" } do |f| %>
      <div class="form-group">
        <%= f.select :device_type, [['Node', 'Node'], ['Gateway', 'Gateway']], {}, { selected: @type, class: "form-control" } %>
      </div>
      <div class="form-group">
        <%= f.text_field :name, class: "form-control", value: @name, placeholder: "Name" %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary", value: "Add"  %>
      </div>
    <% end %>
  </div>
</div>