config/routes.rb
Rails.application.routes.draw do

	root 'network#index'

  #User Login Web Routes
	get 'login', to: 'sessions#new'
	get 'logout', to: 'sessions#destroy'
	post 'sessions', to: 'sessions#create'

  #User Web Routes
	get 'users/list', to: 'users#user_list'
	resources :users, except: [:index, :show]

	#Routes for plugin ajax calls
	get 'plugins/gateway', to: 'plugins#get_gateway'
	get 'plugins/nodes', to: 'plugins#get_nodes'
	get 'plugins/fields', to: 'plugins#get_fields'
	get 'plugins/data', to: 'plugins#get_field_data'
	get 'plugins/commands', to: 'plugins#get_gateway_commands'
	post 'plugins/command', to: 'plugins#create_gateway_command'

  #Plugin Web Routes
  get 'plugins/my_plugins', to: 'plugins#my_plugins'
  get 'plugins/tutorial', to: 'plugins#tutorial'
  resources :plugins, except: [:new]

  #Network Web Routes
	post 'network/connect', to: 'network#connect'
	post 'network/update', to: 'network#update'
	get 'network', to: 'network#index'

  #Node Web Routes
	resources :nodes, only: [:show]
	get 'update', to: 'nodes#update'

  #Gateway Web Routes
	resources :gateways, only: [:show]

  #Access Rights Web Routes
	resources :access_rights, only: [:index, :create, :destroy]

  #Devices Routes
  put 'devices/addlinknodetogateway',to: 'devices#add_link_node_to_gateway'
  put 'devices/removelinknodetogateway',to: 'devices#remove_link_node_to_gateway'
	get 'devices/queuednodecount', to: 'devices#number_of_queued_nodes'
	put 'devices/acceptedqueuednode', to: 'devices#accept_queued_node'
	put 'devices/rejectqueuednode', to: 'devices#reject_queued_node'
	resources :devices

  #Windows Web Routes
	resources :windows, only: [:show, :create, :destroy] do
		member do 
			put :backward
			put :forward
			put :resize
		end
	end

  #Command Web Routes
	resources :commands, only: [:show, :create, :destroy, :update]do
		member do 
			get :execute
      get :next
		end
  end
  post 'commands/:command_id/parameter', to: 'commands#create_param'
	put 'commands/:command_id/parameter/:param_id', to: 'commands#update_param'
	delete 'commands/:command_id/parameter/:param_id', to: 'commands#destroy_param'
	#get 'commands/next', to: 'commands#next'

  #Field Web Routes
	resources :fields, only: [:create, :update, :destroy]

  #Data Web Routes
	resources :data, only: [:index, :create]
  get 'data/export_data', to: 'data#export_data'

  #Settings Web Routes
  get 'settings/nodetypes', to: 'settings#picklist'
	get 'settings/commandtypes', to: 'settings#picklist'
  resources :settings, only: [:index, :update, :destroy]

  ### MOBILE API ROUTES ###
  namespace :mobileapi do
    #Data
		put 'data', to: 'data#create', defaults: {format: :json}
		post 'data', to: 'data#create_mult', defaults: {format: :json}
		post 'datafile', to: 'data#create_via_file', defaults: {format: :json}

    #Commands
    get 'command', to: 'command#show', defaults: {format: :json}
    put 'command', to: 'command#next', defaults: {format: :json}

    #Devices
    put 'devices/approvalrequest', to: 'device_approval_queue#device_approval_request', defaults: {format: :json}
    post 'devices/approvalrequest', to: 'device_approval_queue#device_approval_request', defaults: {format: :json}
    get 'devices', to: 'device_approval_queue#registered_devices', defaults: {format: :json}
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authorize

  def index

  end

  def picklist
    @settings = Setting.where(item_code: params[:item_code])
    @item_code = params[:item_code]
    render :action => '/picklist'
  end

  def update
    id = params[:id].to_i

    begin
      setting = Setting.where(id:id)
      if setting.empty?
        setting = Setting.new item_code:params[:item_code], item_description:params[:item_description]
      else
        setting.item_code = params[:item_code]
        setting.item_description = params[:item_description]
      end

      if setting.save
        render json: {success: "Successfully saved setting", setting: setting}
      else
        render json: {error: "Unabled to save setting"}
      end
    rescue
      render json: {error: "An error occurred trying to update setting"}
    end
  end

  def destroy
    setting = Setting.find(params[:id])
    if setting.destroy
      render json: {success: "Successfully deleted setting"}
    else
      render json: {error: "Error occurred deleting setting"}
    end
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_dropdown.html.erb
<% allitems = picklist.clone %>
<% if !selected.nil? && !selected.blank? && selected != ''%>
    <% if !allitems.nil? && allitems.length > 0 %>
        <% if !allitems.include?(selected)%>
            <% allitems.unshift(selected) %>
            <% disable = selected %>
        <% end %>
    <% else %>
    <% end %>
<% end %>

<% if !allitems.nil? && allitems.length > 0 %>
    <%= select(object, parameter, options_for_select(allitems.map { |type| [type] }, selected: selected, disabled: disable), {include_blank: true}, {class:"form-control selectpicker"})%>
<% else %>
    <%= select(object, parameter, [], {:include_blank => true}, {class:"form-control selectpicker"})%>
<% end %>

app/views/settings/index.html.erb
<div class="row">
  <h4 class="breadcrumb">
    Settings
  </h4>
</div>

<div class="row">
  <div class="col-md-12">
    <ul>
      <li><%= link_to 'Field Type Picklist', settings_nodetypes_path(item_code:'nodetype') %></li>
      <li><%= link_to 'Command Type Picklist', settings_commandtypes_path(item_code:'commandtype') %></li>
      <li><%= link_to 'Command Parameter Type Picklist', settings_commandtypes_path(item_code:'commandparamtype') %></li>
    </ul>
  </div>
</div>

app/views/settings/picklist.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'settings/picklist' %>
  <%= stylesheet_link_tag 'settings/picklist' %>
<% end %>

<div class="row">
  <h4 class="breadcrumb">
    <%= render 'layouts/backbutton' %>
    Picklist Edit
    <button class="btn btn-primary" id="add-item" onclick="newItem('<%= @item_code %>');">Add Item</button>
  </h4>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-striped" id="itemTable">
      <thead>
      <tr>
        <th><label>Description</label></th>
        <th><label>Created</label></th>
        <th><label>Updated</label></th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
      </tr>
      </thead>
      <tbody>
      <% if @settings.any? %>
          <% @settings.each do |setting| %>
              <tr>
                <td class="description">
                  <label id="description"><%= setting.item_description %></label>
                  <input id="description" class="form-control" value="<%= setting.item_description %>" type="text" style="display:none;"/>
                  <input id="setting_id" value="<%= setting.id %>" type="hidden"/>
                  <input id="item_code" value="<%= setting.item_code %>" type="hidden"/>
                </td>
                <td class="created"><label id="createdAt"><%= setting.created_at %></label></td>
                <td class="updated"><label id="updatedAt"><%= setting.updated_at %></label></td>
                <td class="edit-save">
                  <button id="editItem" class="btn btn-primary" onclick="editItem(this);">Edit</button>
                  <button id="saveItem" class="btn btn-primary" onclick="saveItem(this);" style="display:none;">Save</button>
                </td>
                <td class="delete-cancel">
                  <button id="deleteItem" class="btn btn-primary" onclick="deleteItem(this);">Delete</button>
                  <button id="cancelItem" class="btn btn-primary" onclick="cancelItem(this);" style="display:none;">Cancel</button>
                </td>
              </tr>
              <% end %>
          <% end %>
      </tbody>
    </table>
  </div>
</div>