config/routes.rb
Rails.application.routes.draw do

	root 'network#index'

  #User Login Web Routes
	get 'login', to: 'sessions#new'
	get 'logout', to: 'sessions#destroy'
	post 'sessions', to: 'sessions#create'

  #User Web Routes
	get 'users/list', to: 'users#user_list'
	resources :users, except: [:index, :show]

	#Routes for plugin ajax calls
	get 'plugins/gateway', to: 'plugins#get_gateway'
	get 'plugins/nodes', to: 'plugins#get_nodes'
	get 'plugins/fields', to: 'plugins#get_fields'
	get 'plugins/data', to: 'plugins#get_field_data'
	get 'plugins/commands', to: 'plugins#get_gateway_commands'
	post 'plugins/command', to: 'plugins#create_gateway_command'

  #Plugin Web Routes
  get 'plugins/my_plugins', to: 'plugins#my_plugins'
  get 'plugins/tutorial', to: 'plugins#tutorial'
  resources :plugins, except: [:new]

  #Network Web Routes
	post 'network/connect', to: 'network#connect'
	post 'network/update', to: 'network#update'
	get 'network', to: 'network#index'

  #Node Web Routes
	resources :nodes, only: [:show]
	get 'update', to: 'nodes#update'

  #Gateway Web Routes
	resources :gateways, only: [:show]

  #Access Rights Web Routes
	resources :access_rights, only: [:index, :create, :destroy]

  #Devices Routes
  put 'devices/addlinknodetogateway',to: 'devices#add_link_node_to_gateway'
  put 'devices/removelinknodetogateway',to: 'devices#remove_link_node_to_gateway'
	get 'devices/queuednodecount', to: 'devices#number_of_queued_nodes'
	put 'devices/acceptedqueuednode', to: 'devices#accept_queued_node'
	put 'devices/rejectqueuednode', to: 'devices#reject_queued_node'
	resources :devices

  #Windows Web Routes
	resources :windows, only: [:show, :create, :destroy] do
		member do 
			put :backward
			put :forward
			put :resize
		end
	end

  #Command Web Routes
	resources :commands, only: [:show, :create, :destroy, :update]do
		member do 
			get :execute
      get :next
		end
  end
  post 'commands/:command_id/parameter', to: 'commands#create_param'
	put 'commands/:command_id/parameter/:param_id', to: 'commands#update_param'
	delete 'commands/:command_id/parameter/:param_id', to: 'commands#destroy_param'
	#get 'commands/next', to: 'commands#next'

  #Field Web Routes
	resources :fields, only: [:create, :update, :destroy]

  #Data Web Routes
	resources :data, only: [:index, :create]
  get 'data/export_data', to: 'data#export_data'

  #Settings Web Routes
  get 'settings/nodetypes', to: 'settings#picklist'
	get 'settings/commandtypes', to: 'settings#picklist'
  resources :settings, only: [:index, :update, :destroy]

  ### MOBILE API ROUTES ###
  namespace :mobileapi do
    #Data
		put 'data', to: 'data#create', defaults: {format: :json}
		post 'data', to: 'data#create_mult', defaults: {format: :json}
		post 'datafile', to: 'data#create_via_file', defaults: {format: :json}

    #Commands
    get 'command', to: 'command#show', defaults: {format: :json}
    put 'command', to: 'command#next', defaults: {format: :json}

    #Devices
    put 'devices/approvalrequest', to: 'device_approval_queue#device_approval_request', defaults: {format: :json}
    post 'devices/approvalrequest', to: 'device_approval_queue#device_approval_request', defaults: {format: :json}
    get 'devices', to: 'device_approval_queue#registered_devices', defaults: {format: :json}
  end
end

app/controllers/gateways_controller.rb
class GatewaysController < ApplicationController
	before_filter :authorize

	def show
		@gateway = current_user.devices.find_by_id params[:id]
		if @gateway
			@plugins = Plugin.where(type: :Gateway)
				.where(is_protected: false)
				.concat(current_user.plugins.where(type: :Gateway))
				.uniq
			@windows = @gateway.windows.order(:index)
			nodes = []
			@child_count = 0
			begin
				@child_count = DeviceToDeviceLink.where(parent:@gateway.id).count(:child)
				links = DeviceToDeviceLink.where(parent:@gateway.id,child:current_user.access_rights.select(:device_id))
				links.each do |link|
					node = Device.find(link.child)
					nodes.push(node)
				end
			end
			@nodes = nodes

			commands = []
			begin
				@nodes.each do |node|
					node_commands = node.commands.order(priority: :asc, created_at: :asc)
					if node_commands
						node_commands.each do |command|
							commands.push(command)
						end
					end
				end
				gateway_commands = @gateway.commands.order(priority: :asc, created_at: :asc)
				gateway_commands.each do |command|
					commands.push(command)
				end
			end
			@commands = commands.sort_by{|c| [c.priority, c.created_at] }

			settings = Setting.where(item_code: 'commandtype')
			@command_types = []
			if !settings.nil? && !settings.empty?
				settings.map do |setting|
					@command_types << setting.item_description
				end
			end

			settings = Setting.where(item_code: 'commandparamtype')
			@command_param_types = []
			if !settings.nil? && !settings.empty?
				settings.map do |setting|
					@command_param_types << setting.item_description
				end
			end
		elsif Gateway.find_by_id params[:id]
			flash[:error] = 'User does not have access rights to the gateway'
			redirect_to network_path
		else
			flash[:error] = 'Gateway does not exist'
			redirect_to network_path
		end
	end

end

app/helpers/gateways_helper.rb
module GatewaysHelper
end

app/views/gateways/show.html.erb
<% content_for :head do %>
	<%= javascript_include_tag 'devices/device_show' %>
	<%= javascript_include_tag 'gateway_show' %>
  <%= javascript_include_tag 'command' %>
	<%= stylesheet_link_tag 'devices/devices' %>
	<%= stylesheet_link_tag 'gateways' %>
  <%= stylesheet_link_tag 'command' %>
<% end %>

<div class="row"> 
	<h4 class="breadcrumb">
    <%= render 'layouts/backbutton' %>
    <%= t('gateway_view') %>
  </h4>
</div>

<div id="gateway-container" class="row" data-id="<%=@gateway.id%>">
	<ul class="nav nav-tabs">
		<li role="presentation" class="active"><a href="javascript:;" id="dock-link"><%= t('gateway_dock') %></a></li>
		<li role="presentation"><a href="javascript:;" id="commands-link"><%= t('gateway_commands') %></a></li>
    <li role="presentation"><a href="javascript:;" id="nodes-link">Nodes</a></li>
	</ul>

	<div id="gateway-dock">
    <div class="dock-form well well-sm">
      <% unless @plugins.nil? %>
        <%= form_for :window, url: windows_path, method: :post, html: { class: "form-inline" } do |f| %>
          <div class="form-group">
            <% p_list = @plugins.map{|p| [p.name, p.id]}.unshift(['','Default']) %>
            <%= f.select :plugin_id, p_list, {}, { selected: 'Default', class: "form-control" } %>
          </div>
          <div class="form-group" style="display:none;">
            <%= f.text_field :device_id, value: @gateway.id %>
          </div>
          <div class="form-group">
            <%= f.submit class: "btn btn-primary", value: t('window_add')  %>
          </div>
        <% end %>
      <% end %>
    </div>

    <% unless @windows.nil? %>
      <% @windows.each do |window| %>
        <%= render "windows/show", window: window, device_id: @gateway.id%>
      <% end %>
    <% end %>
	</div>

	<div id="gateway-commands" style="display:none">
		<% unless @commands.nil? %>
      <div class="panel">
        <div class="panel panel-default command-panel-header">
          <div class="header centerText col-sm-1"><label><%= t('gateway_command_active') %></label></div>
          <div class="header centerText col-sm-2"><label><%= t('gateway_command_device') %></label></div>
          <div class="header centerText col-sm-4"><label><%= t('gateway_command_name') %></label></div>
          <div class="header centerText col-sm-1"><label><%= t('gateway_command_priority') %></label></div>
          <div class="header centerText col-sm-3">&nbsp;</div>
          <div class="header centerText col-sm-1">&nbsp;</div>
        </div>
        <div>
          <% @commands.each do |command| %>
            <%= render 'commands/form', command: command, gateway: @gateway%>
          <% end %>
        </div>
      </div>
		<% end %>
    <%= form_for :command, url: command_path, html: { class: "form-group row field-form" } do |f| %>
        <%= f.text_field :gateway_id, value: @gateway.id, style: 'display:none;' %>
        <div class="col-sm-12">
          <div class="col-sm-1" style="text-align: center;vertical-align: middle;">
            <label>
              <%= f.check_box( :active, value: false, class: "commandActive" )%>
            </label>
          </div>
          <div class="col-sm-2">
            <%= f.select(:device_id, options_for_select(@nodes.map { |node| [node.name, node.id] }), {include_blank: true}, {class:"form-control selectpicker"})%>
          </div>
          <div class="col-sm-4">
            <%= render 'settings/dropdown', selected: '', picklist: @command_types, object: "command", parameter: "name" %>
          </div>
          <div class="col-sm-1">
            <%= f.number_field( :priority, value: '1', step: 1, min: 1, class: "form-control setting-text" )%>
          </div>
          <div class="col-sm-3">
            <button type="button" href="javascript:;" class="_addCommand btn btn-primary"><%= t('gateway_addcommand') %></button>
          </div>
          <div class="col-sm-1">&nbsp</div>
        </div>
    <% end %>
	</div>

  <div id="gateway-nodes" style="display:none">
    <div class="col-md-12">
      <table class="table table-striped Node">
        <thead>
          <tr>
            <th>Connected Nodes</th>
          </tr>
        </thead>
        <tbody>
          <% if @nodes.length < @child_count %>
            <tr>
              <td>You do not have permission to view some or all of the connected nodes</td>
            </tr>
          <% end %>
          <% @nodes.each do |node| %>
            <tr>
              <td> <h4><%= link_to node.name, device_path(node.id) %></h4> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>